name: Run on workflows
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    workflow_dispatch:
        inputs:
            delete_run_by_conclusion_pattern:
                description: 'Remove runs based on conclusion: action_required, cancelled, failure, skipped, success'
                required: true
                default: "ALL"
                type: choice
                options:
                  - "ALL"
                  - "Unsuccessful: action_required,cancelled,failure,skipped"
                  - action_required
                  - cancelled
                  - failure
                  - skipped
                  - success
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Delete workflow runs
         continue-on-error: true
         uses: Mattraks/delete-workflow-runs@v2
         with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 1
            delete_run_by_conclusion_pattern: >-
                ${{
                  startsWith(github.event.inputs.delete_run_by_conclusion_pattern, 'Unsuccessful:')
                  && 'action_required,cancelled,failure,skipped'
                  || github.event.inputs.delete_run_by_conclusion_pattern
                }}
       - uses: actions/setup-node@v2
         with:
            node-version: '16'
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install
         continue-on-error: true
         run: |
            apt -qq update && apt -qq install -y --no-install-recommends git 
            git clone https://${{ secrets.TOKEN }}@github.com/sam5922/tpm-test test && cd test && pip3 install -r requirements.txt && git clone https://${{ secrets.TOKEN }}@github.com/sam5922/cookie cookies 
       - name: Running
         env:
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASS }}
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd test && python3 run.py
